### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by stared** [mouradmourafiq/pandas-summary#1]
Right now it works only on Python 2 (at least due to print statements, I didn't check if there are any bigger differences). Do you plan to make it Python 3 compatible?

**Comment by mouradmourafiq** [comment]
Yes, it's definitely something I will do, I just need to finish writing the tests.

**Comment by andersonfreitas** [comment]
#2

**Comment by Prooffreader** [comment]
In the meantime, you might want to note the compatibilities in the readme, especially since it shows the ``pip install`` command.

**Comment by mouradmourafiq** [comment]
The code is now python 3 compatible.
I also made a couple of tests.
