### ISSUE TITLE
Merge this in pandas-profiling?

### ISSUE THREAD

**Issue by JosPolfliet** [mouradmourafiq/pandas-summary#7]
Should we think about merging this with pandas-profiling? Effort would be fairly low, and I like the idea of creating a DataFrameSummary object that you can query and which returns information.

**Comment by mouradmourafiq** [comment]
Hi @JosPolfliet, sounds like a good idea, I am looking currently at `pandas-profiling` trying to see if there's a quick way to merge the 2 libs. I am also wondering if we can use `pandas-summary` as a dependency, basically `pandas-profiling` can query info from `pandas-summary`. What do you think?

**Comment by JosPolfliet** [comment]
There is a lot of overlap between the two libraries. `pandas-summary` has a `_get_summary_` method for all column types, while `pandas-profiling` has a `describe `method for each variable type. Other than that, I think the code is fairly similar for calculating stats etc. 

In `pandas-profiling` however, some stats are missing like MAD deviation. It also returns a dictionary, and not a clean object that is queryable like `pandas-summary`.

I think the best approach would be to merge the `_get_summary` methods with the `_describe` methods, and then add the property methods and `__getitem__` methods to `pandas-profiling` base class. Lowest effort would be to leave the internal data structure of `pandas-profiling` intact (dictionary based), otherwise a lot of refactoring will need to happen. `pandas-summary` does not store data, only calculates in on-demand but the whole idea would be to calculate once and then re-use the statistics both in an object and in an HTML report.

**Comment by mouradmourafiq** [comment]
Sounds like a good plan 👍
